services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-python
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/backend-for-frontend:${DOCKERHUB_IMAGE_VERSION}
    image: ${IMAGE_REPO_USER}/backend-for-frontend:${WORKSHOP_VERSION}
    ports:
      - "10115:10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend-python

  # Node, because I have some interesting feature flag stuff to show
  meminator:
    build:
      context: services/meminator-nodejs
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/meminator:${DOCKERHUB_IMAGE_VERSION}
    image: ${IMAGE_REPO_USER}/meminator:${WORKSHOP_VERSION}
    ports:
      - "10116:10116" # they can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-nodejs

  # Java, for variety. I brought it one service from jessitron/meminator, which copied it from Howard's impl
  phrase-picker:
    build:
      context: services/phrase-picker-java
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/phrase-picker:${DOCKERHUB_IMAGE_VERSION}
    image: ${IMAGE_REPO_USER}/phrase-picker:${WORKSHOP_VERSION}
    ports:
      - "10117:10117" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-java

  # .NET, for variety
  image-picker:
    build:
      context: services/image-picker-dotnet
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/image-picker:${DOCKERHUB_IMAGE_VERSION}
    image: ${IMAGE_REPO_USER}/image-picker:${WORKSHOP_VERSION}
    ports:
      - "10118:10118" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-dotnet

  # python, because it has sqlite3 instrumentation
  user-service:
    build:
      context: .
      dockerfile: services/user-service-python/Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/user-service:${DOCKERHUB_IMAGE_VERSION}
    image: ${IMAGE_REPO_USER}/user-service:${WORKSHOP_VERSION}
    ports:
      - "10119:10119"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=user-service-python
    volumes:
      - dbdata:/app/shared-data:ro

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/web:${DOCKERHUB_IMAGE_VERSION}
      args:
        HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
    image: ${IMAGE_REPO_USER}/web:${WORKSHOP_VERSION}
    volumes: # uncomment this for faster development on the frontend
      - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114" # Expose port 10114, that is where it should be listening now

  init-db:
    build:
      context: services/shared-data
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE_REPO_USER}/init-db:${DOCKERHUB_IMAGE_VERSION}
    image: ${IMAGE_REPO_USER}/init-db:${WORKSHOP_VERSION}
    volumes:
      - dbdata:/put-the-db-here
    command: cp /db/users.db /put-the-db-here/

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./services/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - HONEYCOMB_API_KEY=hcaik_01jvrszy8nfbkpdvj26tyn2997pd5vv342j1jf86ekge1pcwcxrncqtf0p

volumes:
  dbdata:
