services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-python
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/backend-for-frontend:${WORKSHOP_VERSION}
    ports:
      - "10115:10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend-python

# Node, because I have some interesting feature flag stuff to show
  meminator:
    build:
      context: services/meminator-nodejs
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/meminator:${WORKSHOP_VERSION}
    ports:
      - "10116:10116" # they can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-nodejs

# .NET, for variety
  phrase-picker:
    build:
      context: services/phrase-picker-java
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/phrase-picker:${WORKSHOP_VERSION}
    ports:
      - "10117:10117" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-java

  image-picker:
    build:
      context: services/image-picker-dotnet
      dockerfile: Dockerfile
    image: ${IMAGE_REPO_USER}/image-picker:${WORKSHOP_VERSION}
    ports:
      - "10118:10118" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-dotnet

# python, because it has sqlite3 instrumentation
  user-service:
    build:
      context: .
      dockerfile: services/user-service-python/Dockerfile
    image: ${IMAGE_REPO_USER}/user-service:${WORKSHOP_VERSION}
    ports:
      - "10119:10119"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=user-service-python
    volumes:
      - ./services/shared-data:/app/shared-data

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
    image: ${IMAGE_REPO_USER}/web:${WORKSHOP_VERSION}
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114" # Expose port 10114, that is where it should be listening now

