services:
  backend-for-frontend:
    build:
      context: services/backend-for-frontend-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
      platforms:
        # this is useful for pushing to Dockerhub, not for local builds
        - linux/amd64
        - linux/arm64
    image: ${IMAGE_REPO_USER}/backend-for-frontend:${PROGRAMMING_LANGUAGE}-${DOCKERHUB_IMAGE_VERSION}
    ports:
      - "10115:10115" # Expose the port your Express app is listening on
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=backend-for-frontend-${PROGRAMMING_LANGUAGE}

  meminator:
    build:
      context: services/meminator-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: ${IMAGE_REPO_USER}/meminator:${PROGRAMMING_LANGUAGE}-${DOCKERHUB_IMAGE_VERSION}
    ports:
      - "10116:10116" # they can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=meminator-${PROGRAMMING_LANGUAGE}

  phrase-picker:
    build:
      context: services/phrase-picker-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: ${IMAGE_REPO_USER}/phrase-picker:${PROGRAMMING_LANGUAGE}-${DOCKERHUB_IMAGE_VERSION}
    ports:
      - "10117:10117" # the outer ports can't be the same
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=phrase-picker-${PROGRAMMING_LANGUAGE}

  image-picker:
    build:
      context: services/image-picker-${PROGRAMMING_LANGUAGE}
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: ${IMAGE_REPO_USER}/image-picker:${PROGRAMMING_LANGUAGE}-${DOCKERHUB_IMAGE_VERSION}
    ports:
      - "10118:10118" # the outer ports can't be the same
    environment:
      - BUCKET_NAME
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_SERVICE_NAME=image-picker-${PROGRAMMING_LANGUAGE}

  web:
    build:
      context: services/web
      dockerfile: Dockerfile
      args:
        HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
      platforms:
        - linux/amd64
        - linux/arm64
    image: ${IMAGE_REPO_USER}/web:${DOCKERHUB_IMAGE_VERSION}
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "10114:10114" # Expose port 10114, that is where it should be listening now

  otel-collector:
    image: otel/opentelemetry-collector-contrib:${COLLECTOR_VERSION}
    ports:
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
    volumes:
      - ./services/otel-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      - HONEYCOMB_API_KEY
